on: [push, pull_request]

jobs:
    build_simppru_job:
        runs-on: ubuntu-latest
        name: This will test simppru on amd64 machine
        steps: 
            - name: Checkout
              uses: actions/checkout@v2
            - name: preconfig
              run: sudo docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
            - name: test inside docker arm32
              uses: ./.github/action_test_amd64
            - name: postconfig
              run: ls build -l